version: '3'
services:
  postgres:
      image: postgres
      ports: 
        - "5433:5432"
      volumes:
        - ./postgresdata/:/data/postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=@Quepasaepi9
        - POSTGRES_DB=strapi
        - PGDATA=/data/postgres
      container_name: postgres_container
      restart: always
  backend:
    image: joshu19/prueba:latest
    depends_on:
      - postgres
    ports: 
      - "4445:4444"
    volumes:
      - ./backend:/app
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=4444
      - APP_KEYS=99gSboF5sbJBZ6UDsoBstA==,T5wwkBTNacI6tEb87b0IVw==,F4qrdi0BqvZQWSUq0QfOtw==,F5P4cS7GTMOhMVXuYiIOJg==
      - API_TOKEN_SALT=96HFtLFVUcp6FZUp7lrFZQ==
      - ADMIN_JWT_SECRET=gn16N/VZn9aUV65SNu12uw==
      - JWT_SECRET=z+HnmVgoic4m81RVkwh7JQ==
      - DATABASE_HOST=postgres_container
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=@Quepasaepi9
      - STRAPI_LICENSE=T1hNb2dUVHBUVGpOTjlMM2RVUzJTWS94b015Z1FhUUk1WWwrMzZQRXVtV25vWVRuVDFtd1BEZkxDWDlqSzNtU2VOTmJlRFJseXJxdWUvQWRuNmVrbys1d2w5YjRkYW9CR1p1TUd0aXB3QlNqbTdOYzhsb3VtWHZvZlYxbEZPWHl1bVI2Q1dySkg2bUUwZDhlQkFMWkIwMnQ5UHpyTDNzUFNmQzNjeE5yS1Z5akh3MHpkeWlWOTJaN2txM1d1UmJmVStKQVNkRjRlQm9iVTgwaXo0WGljVTRLeU9NeStCVExpKzNOVXd0YVQ3L3pBL2xVa3QxL2llTGhGWS9yWXlqb3d1VGhVM1lOdTNlVkw0NHVrVzUycGlPWWFSWDZaM015QzVhandFTUZEaExwSmgwZ3VHOGIvWWxtbmdpV2J4Tk9kc3Nad1gxUkN0dXdzMGpOTkhnTGdBPT0KZXlKMGVYQmxJam9pWW5KdmJucGxJaXdpYVhOVWNtbGhiQ0k2ZEhKMVpTd2liR2xqWlc1elpVdGxlU0k2SW1FMk5tRmhOR0psTFRFd05Ea3RORFZoTUMwNU5URTNMVEkxT0RZM1pXVTFNbVEyTlNJc0ltTjFjM1J2YldWeVNXUWlPaUpCZW5GVFEzbFVOalpPYjI1U05UVTBiQ0lzSW5OMVluTmpjbWx3ZEdsdmJrbGtJam9pUVhwNVdGcDFWRFkyVG1nemRUVXpWMVVpTENKamNtVmhkR1ZrUVhRaU9qRTJOVEkzT1RjNU56RTRPRFlzSW1WNGNHbHlaVUYwSWpveE5qVTBNREEzTlRZME1EQXdmUT09
  frontend:
    image: joshu19/prueba:latest
    depends_on:
      - backend
    ports: 
      - "3001:3000"
    volumes:
      - ./frontend:/app
    restart: always
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:4445/api
      - GOOGLE_ID=181889887025-oducq2l9b0f90ps0vflfqmj8j5hc401u.apps.googleusercontent.com
      - GOOGLE_SECRET=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
      - NEXTAUTH_URL=http://localhost:3001
      - NEXTAUTH_SECRET="49dc52e6bf2abe5ef6e2bb5b0f1ee2d765b922ae6cc8b95d39dc06c21c848f8c"
      - JWT_SECRET="49dc52e6bf2abe5ef6e2bb5b0f1ee2d765b922ae6cc8b95d39dc06c21c848f8c"