import Head from "next/head";
import Image from "next/image";
import Layout from "../components/layout";
import getArticles from "../queries/articles";
import getCategories from "../queries/categories";
import getHomePage from "../queries/homepage";
import styles from "../styles/Home.module.css";
import client from "../apollo-client";
import { getQuery } from "../queries";

export default function Home({ articles, categories, homepage }) {
  console.log(articles);
  // console.log(categories);
  // console.log(homepage);
  return (
    <Layout categories={categories}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <h5 className={styles.title}>
            Las mejores noticias de {homepage.hero.title}
          </h5>
        </main>

        <footer className={styles.footer}>Powered by Joshu</footer>
      </div>
    </Layout>
  );
}

export async function getStaticProps() {
  // const { data: articlesData } = await client.query({
  //   query: getArticles(1, 3),
  // });
  const { data: articlesData } = await getQuery(getArticles, 1, 4);
  // const { data: categoriesData } = await client.query({
  //   query: getCategories(),
  // });
  const { data: categoriesData } = await getQuery(getCategories);

  // const { data: homePageData } = await client.query({
  //   query: getHomePage(),
  // });
  const { data: homePageData } = await getQuery(getHomePage);
  return {
    props: {
      articles: articlesData.articles,
      categories: categoriesData.categories.data,
      homepage: homePageData.homepage.data.attributes,
    },
  };
}
// export async function getStaticProps() {
//   const { data } = await client.query({
//     query: getCategories(),
//   });
//   return {
//     props: {
//       categories: data.categories.data,
//     },
//   };
// }
